# Add this BEFORE the plugins list
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# Set prefix(leader key to Ctrl+l)
set -g prefix C-q
unbind C-b
bind C-q send-prefix

# Screen split planel
unbind %
unbind '"'

bind-key -n C-v split-window -h 
bind-key -n C-a split-window -v 

# Resource 
unbind r 
bind r source-file ~/.tmux.conf

# enable mouse Support 
set -g mouse on 

# Press (prefix + I) for Install plugins
# Press (prefix + alt + u) for Uninstall pluign
# Press (prefix + U) for Update plugins

# enable tpm Pluign manager for tmux and list of plugins
set -g @pluign 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensibleine'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'vaaleyard/tmux-dotbar'

# plugin key-binding
bind -r j resize-pane -D 5 
bind -r k resize-pane -U 5 
bind -r l resize-pane -R 5 
bind -r h resize-pane -L 5 

# Plugin Configuraitons
set -g @resurrent-capture-pane-content 'on'
set -g @continuum-restore 'on'

set -g @tmux-dotbar-bg "#0B0E14"
set -g @tmux-dotbar-fg "#475266"
set -g @tmux-dotbar-fg-current "#BFBDB6"
set -g @tmux-dotbar-fg-session "#565B66"
set -g @tmux-dotbar-fg-prefix "#95E6CB"
set -g @tmux-dotbar-position "bottom"
set -g @tmux-dotbar-justify "absolute-centre"
set -g @tmux-dotbar-left "true"
set -g @tmux-dotbar-right "false"
set -g @tmux-dotbar-session-position "left"
set -g @tmux-dotbar-session-text " #S "
set -g @tmux-dotbar-status-right-text " %H:%M "
set -g @tmux-dotbar-window-status-format " #W "
set -g @tmux-dotbar-window-status-separator " • "
set -g @tmux-dotbar-maximized-icon "󰊓"
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs false
set -g @tmux-dotbar-bold-status false
set -g @tmux-dotbar-bold-current-window false
set -g @tmux-dotbar-ssh-enabled true
set -g @tmux-dotbar-ssh-icon '󰌘'
set -g @tmux-dotbar-ssh-icon-only false

# Initialize TMUX plugin manager(keep this line at very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
