# Set your custom path
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'


# Set prefix(leader key to Ctrl+l)
set -g prefix C-q
unbind C-b
bind C-q send-prefix

# Screen split planel
unbind %
unbind '"'

bind-key -n C-v split-window -h 
bind-key -n C-a split-window -v 

# Resource 
unbind r 
bind r source-file ~/.tmux.conf

# enable mouse Support 
set -g mouse on 

# Press (prefix + I) for Install plugins
# Press (prefix + alt + u) for Uninstall pluign
# Press (prefix + U) for Update plugins

# pop-up Window 
bind f display-popup -w 80% -h 60% -E 
bind H display-popup -w 80% -h 80%  "htop"
bind G display-popup -d "#{pane_current_path}" -w 80% -h 80%  lazygit 
bind T display-popup -E -d "#{pane_current_path}" -w 80% -h 80% -T "Tree View" "zsh -i -c 'eza --tree --icons --color=always | bat --paging=always'"

# enable tpm Pluign manager for tmux and list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'wfxr/tmux-power'

# plugin key-binding
bind -r j resize-pane -D 5 
bind -r k resize-pane -U 5 
bind -r l resize-pane -R 5 
bind -r h resize-pane -L 5 

# Plugin Configuraitons
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @tmux_power_theme 'gold'

# Prefix + I        # install plugins
# Prefix + Ctrl-s   # save
# Prefix + Ctrl-r   # restore



# Initialize TMUX plugin manager(keep this line at very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
